version: '3'
services:
  docker-node-app:
    build: . # Path to Dockerfile
    ports:
      - "3000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=swapnil
      - MONGO_INITDB_ROOT_PASSWORD=Swapnil@67