version: '3'
services:
  docker-node-app:
    build: . # Path to Dockerfile
    ports:
      - "3000:4000"
    volumes:
      - ./:/app # Bind mount
      - /app/node_modules # anonymous volume
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=swapnil
      - MONGO_INITDB_ROOT_PASSWORD=Swapnil@67
    volumes:
      - mongo-db:/data/db # Named Volume
volumes:
  mongo-db: