version: '3'
services:
  docker-node-app:
    build: . # Path to Dockerfile
    ports:
      - "3000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env