version: '3'
services:
  docker-node-app:
    build:
      context: . # Path to Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app # Bind mount
      - /app/node_modules # anonymous volume
    environment:
      - NODE_ENV=development
    command: npm run dev
      